### ISSUE TITLE
Afterburner does not support the new CoercionConfig

### ISSUE THREAD

**Issue by carterkozak** [FasterXML/jackson-modules-base#120]
I have a project which disables scalar coercion, however allows serialization and deserialization of java `long`, `java.lang.Long`, and `java.util.OptionalLong` values as strings to avoid javascript number truncation. Upgrading to 2.12.0 I replaced custom deserializers with CoercionConfig, however optimized accessors fail with:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot coerce JSON VALUE_STRING value ("1") into long (enable `MapperFeature.ALLOW_COERCION_OF_SCALARS` to allow)
 at [Source: (String)"{"value":"1"}"; line: 1, column: 10]

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1603)
	at com.fasterxml.jackson.module.afterburner.deser.OptimizedSettableBeanProperty._verifyScalarCoercion(OptimizedSettableBeanProperty.java:405)
	at com.fasterxml.jackson.module.afterburner.deser.OptimizedSettableBeanProperty._deserializeLong(OptimizedSettableBeanProperty.java:305)
	at com.fasterxml.jackson.module.afterburner.deser.SettableLongMethodProperty.deserializeAndSet(SettableLongMethodProperty.java:40)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4591)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
```

The afterburner module should respect the CoercionConfig, currently it only checks `MapperFeature.ALLOW_COERCION_OF_SCALARS`:
 https://github.com/FasterXML/jackson-modules-base/blob/6876b282d56983cc0296dc1ce5346503d8bc11e6/afterburner/src/main/java/com/fasterxml/jackson/module/afterburner/deser/OptimizedSettableBeanProperty.java#L402-L413

Blackbird appears to be impacted as well (at a glance reading the code, I have not validated with a test yet):
https://github.com/FasterXML/jackson-modules-base/blob/6876b282d56983cc0296dc1ce5346503d8bc11e6/blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/deser/OptimizedSettableBeanProperty.java#L381-L392

**Comment by cowtowncoder** [comment]
Yes, it is very likely that this also affects Blackbird; and yes, improvements are needed to get behavior in line with core databind.

**Comment by carterkozak** [comment]
I should be able to contribute something in the next week or so, no rush to review as you take a well deserved break :-)
The 2.12 upgrade has been incredibly smooth so far!

**Comment by cowtowncoder** [comment]
@carterkozak cool, glad to hear it has been at least somewhat smooth process! It's good to get a sense of various regressions after release, .1 patch often follows within a month. Many users really only test the .0 and not the rcs anyway. :)

I do have my todo-list on

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

and this helps track things that should make it in 2.12.1.

**Comment by cowtowncoder** [comment]
Starting work on this, bigger than I thought but important to get parity.

**Comment by carterkozak** [comment]
Thanks, I really appreciate it! Sorry I hadn't had a chance to put something together myself.

**Comment by cowtowncoder** [comment]
@carterkozak no problem at all, this is quite sizable thing. Also beefing up CoercionConfig testing in databind itself, noticing some gaps.

**Comment by cowtowncoder** [comment]
Ok I think this should work now. Did a sizable detour by first copying quite a bit of handling code from `StdDeserializer`, before realizing that I can delegate non-default input shapes and keep code not only much tighter but also more compliant (since delegating uses default databind handling in that case).

@carterkozak Would appreciate if you could see if snapshot from 2.12 works better at this point.
