### ISSUE TITLE
Help with CNFE with Afterburner creating property accessor class

### ISSUE THREAD

**Issue by mebigfatguy** [FasterXML/jackson-modules-base#121]
Using jackson 2.11.3/Java 1.8 - normal classpath web class loader

I'm seeing CNFE in my logs with afterburner, trying to build a class for 

javax.ws.rs.BadRequestException$Access4
JacksonSerializer76314150'

Which i take it it's trying to build a class to access properties of BadRequestException.

BadRequestException comes out of javax.ws.rs-api.jar version 2.1.1

Looking at that class, i don't see any obviously tricky properties to foul things up. Any ideas what to look for?

 com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'javax.ws.rs.BadRequestException$Access4
JacksonSerializer76314150': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:295) ~[jackson-databi
nd.jar:2.11.3]
#######################################
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_231]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_231]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635) ~[?:1.8.0_231]
	at com.fasterxml.jackson.module.afterburner.util.MyClassLoader.loadAndResolve(MyClassLoader.java:90) ~[jack
son-module-afterburner.jar:2.11.3]

**Comment by cowtowncoder** [comment]
Unfortunately nothing jumps out. Might be worth checking whether 2.11.2 and (just released) 2.12.0 exhibit same problem (to rule out possibility it might be a recent change).

About the only setting to try would be changing state of

    AfterburnerModule.setUseValueClassLoader(false);

but I don't think I would expect that to help here.
