### ISSUE TITLE
JAXB @XmlValue deserializing not working with records

### ISSUE THREAD

**Issue by micopiira** [FasterXML/jackson-modules-base#189]
`@XmlAttribute` and `@XmlElement` seem to work fine with records, and `@XmlValue` seems to work when serializing but deserializing fails with `java.lang.IllegalAccessException`

```java
public class Main {

    public record TestObject (
            @XmlValue
            String name,
            @XmlAttribute
            int age) {}

    public static void main(String[] args) throws JsonProcessingException {
        XmlMapper xmlMapper = new XmlMapper();
        JakartaXmlBindAnnotationModule module = new JakartaXmlBindAnnotationModule();
        xmlMapper.registerModule(module);
        TestObject testObject = new TestObject("foo", 12);
        String xml = xmlMapper.writeValueAsString(testObject);
        TestObject testObject1 = xmlMapper.readValue(xml, TestObject.class);
    }
}
```

stacktrace:

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not set final java.lang.String field org.example.Main$TestObject.name to java.lang.String
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:627)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:615)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:638)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:193)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValue$Regular.assign(PropertyValue.java:60)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:519)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTextDeserializer.deserialize(XmlTextDeserializer.java:96)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at org.example.Main.main(Main.java:25)
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field org.example.Main$TestObject.name to java.lang.String
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
	at java.base/java.lang.reflect.Field.set(Field.java:799)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:190)
	... 12 more
```

**Comment by cowtowncoder** [comment]
I suspect this is related to general issues with annotation merging, records, to be resolved in `jackson-databind` in (I hope) nearish future (for 2.15).

One challenge here is that it could also be related to XML module handling. It would be great if the issue could be reproduced with Jackson's own annotations, only because then issue could be moved to `jackson-dataformat-xml`; test in this repo cannot depend on XML module.

Actually, I think I'll move this to XML module repo since it can depend on JAXB/Jakarta-Bind annotations but not vice versa.
