### ISSUE TITLE
[guice] fail to inject MapBinder

### ISSUE THREAD

**Issue by todylu** [FasterXML/jackson-modules-base#43]
[MapBinder](http://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/multibindings/MapBinder.html)
```
final class Configure {
    @Inject
    private Map<String, WorkspaceFactory> factoryMap;
    ... ...
}
```

When I want to deserialize json:  `Configure configure = mapper.readValue(file, Configure.class);`. I get the following errors:

```
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Map was bound.
  while locating java.util.Map

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1081)
	at com.fasterxml.jackson.module.guice.GuiceInjectableValues.findInjectableValue(GuiceInjectableValues.java:20)
	at com.fasterxml.jackson.databind.DeserializationContext.findInjectableValue(DeserializationContext.java:382)
	at com.fasterxml.jackson.databind.deser.impl.ValueInjector.findValue(ValueInjector.java:45)
	at com.fasterxml.jackson.databind.deser.impl.ValueInjector.inject(ValueInjector.java:51)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.injectValues(BeanDeserializerBase.java:1513)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:354)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
	at net.citrite.gs.I18NSonar.run(I18NSonar.java:69)
	at net.citrite.gs.I18NSonar.main(I18NSonar.java:60)
```

**Comment by cowtowncoder** [comment]
I don't know this module well (or Guice), but from exception it sounds like there is no binding on Guice for type `Map`?

**Comment by todylu** [comment]
I can inject successfully without Jackson Module.
```
    public static void main(String[] args) {
        Injector injector = Guice.createInjector(Stage.PRODUCTION, new BootstrapModule());
        Configure configure = new Configure();
        injector.injectMembers(configure);
        ... ...
   }
```
