### ISSUE TITLE
(jaxb) Jackson doesn't wrap properties with XMLElementWrapper

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-modules-base#45]
(note: moved from https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/69 filed by @GonenI)

Jackson 2.9.4 with `JaxbAnnotationModule` Ignores `@XMLElementWrapper` , and does not add an extra level of wrapping.

For a class looking like this:

```java
@XmlRootElement(name = "revision")
class A {
	private List<Integer> tickets = Arrays.asList(3,4,5);

	@XmlElement(name = "ticket")
	@XmlElementWrapper(name = "tickets")
	public List<Integer> getTickets() {	return tickets; }
}
```
The expected output, and what Jettison outputs is {"tickets":{"ticket":[3,4,5]}}
Jackson ignores the the @XmlElementWrapper wrapping directive and outputs {"ticket":[3,4,5]}

Failing Unit Test:

```java
@XmlRootElement(name = "revision")
class A {
	private List<Integer> tickets = Arrays.asList(3,4,5);

	@XmlElement(name = "ticket")
	@XmlElementWrapper(name = "tickets")
	public List<Integer> getTickets() {	return tickets; }
}
@XmlRootElement(name = "revision")
class B {
	private List<Integer> tickets = Arrays.asList(3,4,5);

	@XmlElement(name = "ticket")
	public List<Integer> getTickets() {	return tickets; }
}
public class XMLElementWrapperTest {

	@Test
	public void test() throws Exception {
		ObjectMapper mapper = new ObjectMapper();
		JaxbAnnotationModule jaxbAnnotationModule = new JaxbAnnotationModule();
		mapper.registerModule(jaxbAnnotationModule);
    	A a = new A(); B b = new B();
   	    Assert.assertNotEquals(mapper.writeValueAsString(a),mapper.writeValueAsString(b)); // Expected output with Element wrapper is {"tickets":{"ticket":[3,4,5]}}
	}
}
```

**Comment by sndptnk** [comment]
Encountered this issue with **JacksonJaxbJsonProvider**
This seems to be impacting serialization as well . Also XML serialization/Deserialization works fine.
Only seems to be an issue with JSON serialization/deserialization honoring JAXB annotations.

**Comment by sndptnk** [comment]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "items" (class com.a.b.c.d.model.Order), not marked as ignorable (11 known properties: "iamount", "tamount", "lkdd", "samount", "ono", "iid", "odate", "hamount", "camount", "item", "s1amount"])
 at [Source: org.apache.cxf.transport.http.AbstractHTTPDestination$1@1ddc7236; line: 53, column: 23] (through reference chain: com.a.b.c.d.model.ARequest["order"]->com.a.b.c.d.model.Order["items"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1489)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:111)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1374)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBody(JAXRSUtils.java:1325)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameter(JAXRSUtils.java:832)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:796)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:212)
	... 32 more

**Comment by tush7986** [comment]
We are also facing the same issue. Do we have any work around to this?

**Comment by djchi82** [comment]
Any movement on this issue. We are facing the same issue in Release 2.11.2

**Comment by cowtowncoder** [comment]
@djchi82 the usual practice here is that if there is progress, notes are made on issue. There are no notes.

But looking at this again, I will consider this invalid; will add an explanation and close the ticket.

**Comment by cowtowncoder** [comment]
There is no wrapping capability on JSON output: it is only used for XML arrays/lists.
Jackson is not a JAXB implementation per se (it just tries to support annotations that make sense given context), and in particular this is one feature that is not necessary for JSON as it has native Array values. Jettison may use it for its own needs (given it transcodes between xml and json apis), but that is not something Jackson does.

So: this particular annotation is only relevant for XML output, not other formats Jackson supports.

**Comment by djchi82** [comment]
> @djchi82 the usual practice here is that if there is progress, notes are made on issue. There are no notes.
> 
> But looking at this again, I will consider this invalid; will add an explanation and close the ticket.

Thank you. I've been looking for a solution to this for 3 days and most references lead to dead ends. I want to make sure other people who are looking aren't finding loose ends and have a valid path to a work around.

Thank you for being on top of the ticket.

**Comment by cowtowncoder** [comment]
Forgot to add one important relevant reference: I _think_ what might be replacement should it get implemented (and while open for long, it is considered viable thing) is hypothetical `@JsonWrapped`:

https://github.com/FasterXML/jackson-databind/issues/512

and if that was done then one could consider use of same underlying mechanism to possibly apply to `@XmlElementWrapper` (although there would be some discussion of exact semantics).

**Comment by raphw** [comment]
Hi, I was seeing if this could be reopened. I noticed an unfortunate mismatch when using JAXB annotations with Jackson when the [XEW plugin](https://github.com/dmak/jaxb-xew-plugin) is involved. As Jackson does not consider the `XmlElementWrapper` annotation, two JAXB annotations that are equivalent to the spec are no longer compatible. If the same XSD is used by a server and client application, where only one uses the XEW plugin, the same JAXB-representation cannot be marshalled and unmarshalled. Consider a wrapped list, once created [with vanilla XJC](https://github.com/raphw/jacksom-xml-element-wrapper/blob/main/src/main/java/org/example/WithoutModule.java#L60) and once created with [XJC using the XEW plugin, or handrolled[(https://github.com/raphw/jacksom-xml-element-wrapper/blob/main/src/main/java/org/example/WithoutModule.java#L91).

Jackson will created different JSON representations:
```json
{"values":{"value":["foo","bar"]}}
{"value":["foo","bar"]}
```
whereas a JAXB compliant implementation would create the same XML:
```xml
<element><values><value>foo</value><value>bar</value></values></element>
```
for both representations as they represent the same specification.

I played a bit with custom serializers/deserializers and laded at a working implementation: https://github.com/raphw/jacksom-xml-element-wrapper - I am by far an expert to deal with these things, maybe you have a better suggestion, but generally, would you consider to add this to Jackson? I think that the deserializer (that supports both the expanded and non-expanded representation) could be active by default whereas the serializer would need some sort of activation to avoid breaking compatibility.

What do you think?

**Comment by cowtowncoder** [comment]
@raphw I am not dead set against this, although the main challenge on implementation remains the same: structural modifications by Jackson are limited and are problematic where they do exist (`@JsonUnwrapped` is bane of my existence :) ).
So recognizing the annotation is not the problem; having some mechanism to enable with it is.
(and in particular on deserialization side: serialization is typically easier to handle... but here that alone would not make sense).

Having said that, if you want this to be reconsidered I think it'd be good to file a new issue, with a reference to this one as background. But explaining the problem from the use case you have (I can see how that is problematic) so reading this issue is not necessary to understand the problem.

**Comment by raphw** [comment]
I created a new ticket with a more formal problem description and solution suggestion. Thanks!
