### ISSUE TITLE
VerifyError in WLS application server

### ISSUE THREAD

**Issue by ghost** [FasterXML/jackson-modules-base#94]
Hi, in our commertial code we faced with such problem on WLS environment.

The following issue reproduces when we are using mapper.registerModule(new AfterburnerModule()):
`java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClassInternal(GenericClassLoader.java:1113)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:1046)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1038)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:990)
	at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:611)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:543)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:496)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:473)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClassInternal(GenericClassLoader.java:1113)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:1046)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1038)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:990)
	at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:611)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:543)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:496)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:473)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at weblogic.utils.classloaders.GenericClassLoader.defineClassInternal(GenericClassLoader.java:1113)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:1046)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1038)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:990)
	at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:611)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:543)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:496)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:473)
	at com.fasterxml.jackson.module.afterburner.deser.PropertyMutatorCollector.addStringSetter(PropertyMutatorCollector.java:62)
	at com.fasterxml.jackson.module.afterburner.deser.DeserializerModifier.findOptimizableProperties(DeserializerModifier.java:138)
	at com.fasterxml.jackson.module.afterburner.deser.DeserializerModifier.updateBuilder(DeserializerModifier.java:58)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:266)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:170)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3908)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3774)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2116)`

Our jackson libs configuration:

lib/jackson-annotations-2.10.0.jar
Implementation-Version: 2.10.0

lib/jackson-core-2.10.0.pr3.jar
Implementation-Version: 2.10.0.pr3

lib/jackson-core-asl-1.9.13.jar
Implementation-Version: 1.9.13

lib/jackson-databind-2.10.0.jar
Implementation-Version: 2.10.0

lib/jackson-dataformat-xml-2.10.0.jar
Implementation-Version: 2.10.0

lib/jackson-jaxrs-1.9.11.jar
Implementation-Version: 1.9.11

lib/jackson-jaxrs-base-2.10.0.pr1.jar
Implementation-Version: 2.10.0.pr1

lib/jackson-jaxrs-json-provider-2.10.0.jar
Implementation-Version: 2.10.0

lib/jackson-mapper-asl-1.9.13.jar
Implementation-Version: 1.9.13

lib/jackson-module-afterburner-2.10.0.jar
Implementation-Version: 2.10.0

lib/jackson-module-jaxb-annotations-2.10.0.jar
Implementation-Version: 2.10.0

lib/jackson-xc-1.9.11.jar
Implementation-Version: 1.9.11

Unfortunately, we dont have a reproducable test case. Problem can be caused by mixin annotations or something else.
Could you please promt where rootcause of this issue can be? Do you have any suggestions regarding problem above? Please help. Thank you.

**Comment by cowtowncoder** [comment]
Unfortunately, I don't really have a good guess. One thing that is probably relevant is JDK/JVM version: I assume this is with JVM newer than Java 8, and is adding some restrictions.
I don't think this is due to mix-ins but due to JVM blocking use of Afterburner-generated optimized `SettableBeanProperty`.

Two settings you might want to try in `AfterburnerModule` are:

* `setUseValueClassLoader(false)`
* `setUseOptimizedBeanDeserializer(false)`

of which second one seems like it might avoid the issue (by disabling one type of optimization).
